/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { MintRequest, mintRequestSchema } from '../models/mintRequest';
import {
  UploadImageRequest,
  uploadImageRequestSchema,
} from '../models/uploadImageRequest';
import { BaseController } from './baseController';

export class UtilsController extends BaseController {
  /**
   * @param body
   * @return Response from the API call
   */
  async uploadImage(
    body: UploadImageRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/utils/upload-image');
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({ body: [body, uploadImageRequestSchema] });
    req.json(mapped.body);
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async mint(
    body: MintRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/utils/mint');
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({ body: [body, mintRequestSchema] });
    req.json(mapped.body);
    return req.call(requestOptions);
  }
}
