/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Billing {
  description: string;
}

export const billingSchema: Schema<Billing> = object({
  description: ['description', string()],
});
