/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChangePasswordRequest {
  password: string;
  newPassword: string;
}

export const changePasswordRequestSchema: Schema<ChangePasswordRequest> = object(
  { password: ['password', string()], newPassword: ['new_password', string()] }
);
