/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import { Billing, billingSchema } from './billing';
import { GroupInvestData, groupInvestDataSchema } from './groupInvestData';

export interface CreateOrderRequest {
  userId: string;
  itemId: string;
  type: string;
  createdAt: number;
  description: string;
  price: number;
  status: string;
  receiver: string;
  amount: number;
  groupInvestData: GroupInvestData;
  billing: Billing;
}

export const createOrderRequestSchema: Schema<CreateOrderRequest> = object({
  userId: ['user_id', string()],
  itemId: ['item_id', string()],
  type: ['type', string()],
  createdAt: ['created_at', number()],
  description: ['description', string()],
  price: ['price', number()],
  status: ['status', string()],
  receiver: ['receiver', string()],
  amount: ['amount', number()],
  groupInvestData: ['group_invest_data', lazy(() => groupInvestDataSchema)],
  billing: ['billing', lazy(() => billingSchema)],
});
