/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { ExtraProperty, extraPropertySchema } from './extraProperty';

export interface DetailInfo {
  richtext: string;
  realEstateStatus: string;
  realEstateLegalStatus: string;
  block: string;
  floor: string;
  totalArea: string;
  usableArea: string;
  numberOfBedRoom: number;
  numberOfBathRoom: number;
  balconyDirection: string;
  viewSight: string;
  doorDirection: string;
  apartmentId: string;
  extraProperties: ExtraProperty[];
}

export const detailInfoSchema: Schema<DetailInfo> = object({
  richtext: ['richtext', string()],
  realEstateStatus: ['real_estate_status', string()],
  realEstateLegalStatus: ['real_estate_legal_status', string()],
  block: ['block', string()],
  floor: ['floor', string()],
  totalArea: ['total_area', string()],
  usableArea: ['usable_area', string()],
  numberOfBedRoom: ['number_of_bed_room', number()],
  numberOfBathRoom: ['number_of_bath_room', number()],
  balconyDirection: ['balcony_direction', string()],
  viewSight: ['view_sight', string()],
  doorDirection: ['door_direction', string()],
  apartmentId: ['apartment_id', string()],
  extraProperties: ['extra_properties', array(lazy(() => extraPropertySchema))],
});
