/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface ExtraProperty {
  key: string;
  value: string;
  isDisplayOnGeneralInfo: boolean;
}

export const extraPropertySchema: Schema<ExtraProperty> = object({
  key: ['key', string()],
  value: ['value', string()],
  isDisplayOnGeneralInfo: ['is_display_on_general_info', boolean()],
});
