/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface GroupInvestData {
  projectId: string;
  quantity: number;
  originalUnitPrice: number;
}

export const groupInvestDataSchema: Schema<GroupInvestData> = object({
  projectId: ['project_id', string()],
  quantity: ['quantity', number()],
  originalUnitPrice: ['original_unit_price', number()],
});
