/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Image {
  imageName: string;
  imageUrl: string;
  uploadedBy: string;
  order: number;
}

export const imageSchema: Schema<Image> = object({
  imageName: ['image_name', string()],
  imageUrl: ['image_url', string()],
  uploadedBy: ['uploaded_by', string()],
  order: ['order', number()],
});
