/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Location1 {
  departmentNumber: string;
  street: string;
  ward: string;
  district: string;
  province: string;
  countryCode: string;
}

export const location1Schema: Schema<Location1> = object({
  departmentNumber: ['department_number', string()],
  street: ['street', string()],
  ward: ['ward', string()],
  district: ['district', string()],
  province: ['province', string()],
  countryCode: ['country_code', string()],
});
