/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Province, provinceSchema } from './province';

export interface Location {
  departmentNumber: string;
  street: string;
  ward: string;
  district: string;
  province: Province;
  countryCode: string;
}

export const locationSchema: Schema<Location> = object({
  departmentNumber: ['department_number', string()],
  street: ['street', string()],
  ward: ['ward', string()],
  district: ['district', string()],
  province: ['province', lazy(() => provinceSchema)],
  countryCode: ['country_code', string()],
});
