/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface LoginRequest {
  username: string;
  password: string;
}

export const loginRequestSchema: Schema<LoginRequest> = object({
  username: ['username', string()],
  password: ['password', string()],
});
