/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { bigint, object, Schema, string } from '../schema';

export interface MintRequest {
  address: string;
  amount: bigint;
}

export const mintRequestSchema: Schema<MintRequest> = object({
  address: ['address', string()],
  amount: ['amount', bigint()],
});
