/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface ProgressionOfProject {
  key: string;
  value: string;
  date: number;
  order: number;
  isActive: boolean;
}

export const progressionOfProjectSchema: Schema<ProgressionOfProject> = object({
  key: ['key', string()],
  value: ['value', string()],
  date: ['date', number()],
  order: ['order', number()],
  isActive: ['is_active', boolean()],
});
