/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Province {
  key: string;
  value: string;
}

export const provinceSchema: Schema<Province> = object({
  key: ['key', string()],
  value: ['value', string()],
});
