/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ReceiveFundsRequest {
  orderId: string;
  confirmedBy: string;
}

export const receiveFundsRequestSchema: Schema<ReceiveFundsRequest> = object({
  orderId: ['order_id', string()],
  confirmedBy: ['confirmed_by', string()],
});
