/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RequestPasswordConfirmRequest {
  username: string;
  token: string;
  password: string;
}

export const requestPasswordConfirmRequestSchema: Schema<RequestPasswordConfirmRequest> = object(
  {
    username: ['username', string()],
    token: ['token', string()],
    password: ['password', string()],
  }
);
