/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ResetPasswordRequest {
  email: string;
}

export const resetPasswordRequestSchema: Schema<ResetPasswordRequest> = object({
  email: ['email', string()],
});
