/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface SetRevenueRequest {
  projectId: string;
  totalRevenue: number;
}

export const setRevenueRequestSchema: Schema<SetRevenueRequest> = object({
  projectId: ['project_id', string()],
  totalRevenue: ['total_revenue', number()],
});
