/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface TransferRequest {
  receiver: string;
  amount: number;
}

export const transferRequestSchema: Schema<TransferRequest> = object({
  receiver: ['receiver', string()],
  amount: ['amount', number()],
});
