/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface UpdateUserInfoRequest {
  firstName: string;
  lastName: string;
  sex: string;
  phone: string;
  birthday: number;
  avatar: string;
}

export const updateUserInfoRequestSchema: Schema<UpdateUserInfoRequest> = object(
  {
    firstName: ['first_name', string()],
    lastName: ['last_name', string()],
    sex: ['sex', string()],
    phone: ['phone', string()],
    birthday: ['birthday', number()],
    avatar: ['avatar', string()],
  }
);
