/**
 * TPA BackendLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UploadImageRequest {
  rawString: string;
  name: string;
}

export const uploadImageRequestSchema: Schema<UploadImageRequest> = object({
  rawString: ['raw_string', string()],
  name: ['name', string()],
});
